K_GAMEMODE = "kA2"
K_IS_MINI = "kA3"
K_SPEED = "kA4"
K_IS_DUAL = "kA8"
K_IS_START_POS = "kA9"
K_IS_TWO_PLAYER = "kA10"
K_IS_FLIPPED_GRAVITY = "kA11"
K_IS_PLATFORMER = "kA22"

K_BG_ID = "kA6"
K_GROUND_ID = "kA7"

K_SONG_OFFSET = "kA13"

K_GUIDELINES = "kA14"

K_SONG_FADE_IN = "kA15"
K_SONG_FADE_OUT = "kA16"

K_LINE_ID = "kA17"

K_FONT_ID = "kA18"

K_MG_ID = "kA25"