KCEK = "kCEK"

LEVEL_NAME = "k2"
DESCRIPTION_BASE64 = "k3"
CREATOR = "k5"
USER_ID = "k6"
DIFFICULTY = "k7"
OFFICIAL_SONG_ID = "k8"
IS_VERIFIED = "k14"
LEVEL_VERSION = "k16"
ATTEMPTS = "k18"
NORMAL_MODE_PERCENTAGE = "k19"
PRACTICE_MODE_PERCENTAGE = "k20"
LEVEL_TYPE = "k21"
LENGTH = "k23"
JUMPS = "k36"

TWO_PLAYER_MODE = "k43"

CUSTOM_SONG_ID = "k45"

BINARY_VERSION = "k50"

HAS_FIRST_COIN = "k61"
HAS_SECOND_COIN = "k62"
HAS_THIRD_COIN = "k63"
COINS = "k64"
ARE_COINS_VERIFIED = "k65"
REQUESTED_STARS = "k66"

SECS_SPENT_EDITING = "k80"
SECS_SPENT_EDITING_PREVIOUS_COPIES = "k81"

###################

LEVEL_TYPE_OFFICIAL = 1
LEVEL_TYPE_LOCAL = 2
LEVEL_TYPE_SAVED = 3
LEVEL_TYPE_ONLINE = 4