K_KCEK = "kCEK"

K_LEVEL_NAME = "k2"
K_DESCRIPTION_BASE64 = "k3"
K_CREATOR = "k5"
K_USER_ID = "k6"
K_DIFFICULTY = "k7"
K_OFFICIAL_SONG_ID = "k8"
K_IS_VERIFIED = "k14"
K_LEVEL_VERSION = "k16"
K_ATTEMPTS = "k18"
K_NORMAL_MODE_PERCENTAGE = "k19"
K_PRACTICE_MODE_PERCENTAGE = "k20"
K_LEVEL_TYPE = "k21"
K_LENGTH = "k23"
K_JUMPS = "k36"

K_TWO_PLAYER_MODE = "k43"

K_CUSTOM_SONG_ID = "k45"

K_BINARY_VERSION = "k50"

K_HAS_FIRST_COIN = "k61"
K_HAS_SECOND_COIN = "k62"
K_HAS_THIRD_COIN = "k63"
K_COINS = "k64"
K_ARE_COINS_VERIFIED = "k65"
K_REQUESTED_STARS = "k66"

K_SECS_SPENT_EDITING = "k80"
K_SECS_SPENT_EDITING_PREVIOUS_COPIES = "k81"

###################

LEVEL_TYPE_OFFICIAL = 1
LEVEL_TYPE_LOCAL = 2
LEVEL_TYPE_SAVED = 3
LEVEL_TYPE_ONLINE = 4