ID = 1
POS_X = 2
POS_Y = 3
FLIPPED_H = 4
FLIPPED_V = 5
ROTATION_DEGREES = 6

TRIGGER_RED = 7
TRIGGER_GREEN = 8
TRIGGER_BLUE = 9
TRIGGER_DURATION = 10
TRIGGER_IS_TOUCH_TRIGGERED = 11

SECRET_COIN_ID = 12

SPECIAL_CHECKED = 13

TRIGGER_IS_PLAYER_COLOR_1 = 15
TRIGGER_IS_PLAYER_COLOR_2 = 16

TRIGGER_IS_BLENDING = 17

EDITOR_LAYER_1 = 20

COLOR_CHANNEL_DETAIL = 21
COLOR_CHANNEL_BASE = 22

TARGET_COLOR_ID = 23

Z_LAYER = 24
Z_ORDER = 25

MOVE_OFFSET_X = 28
MOVE_OFFSET_Y = 29

EASING = 30

TEXT = 31

IS_GROUP_PARENT = 34

TRIGGER_OPACITY = 35

HSV_DETAIL_ENABLED = 41
HSV_BASE_ENABLED = 42
HSV_DETAIL = 43
HSV_BASE = 44

TRIGGER_PULSE_FADE_IN = 45
TRIGGER_PULSE_HOLD = 46
TRIGGER_PULSE_FADE_OUT = 47
TRIGGER_PULSE_MODE = 48

TRIGGER_COPIED_COLOR_HSV = 49
TRIGGER_COPIED_COLOR_ID = 50
TRIGGER_TARGET_GROUP_ID = 51

TRIGGER_PULSE_TARGET_TYPE = 52

TELEPORT_YELLOW_OFFSET_Y = 54
TELEPORT_PORTAL_IS_SMOOTH_EASE = 55

TRIGGER_DO_ACTIVATE_GROUP = 56

GROUPS = 57

TRIGGER_MOVE_LOCK_TO_PLAYER_X = 58
TRIGGER_MOVE_LOCK_TO_PLAYER_Y = 59

TRIGGER_COPY_OPACITY = 60

EDITOR_LAYER_2 = 61

IS_SPAWN_TRIGGERED = 62
SPAWN_DELAY = 63

DONT_FADE = 64

TRIGGER_PULSE_BASE_ONLY = 65
TRIGGER_PULSE_DETAIL_ONLY = 66

DONT_ENTER = 67

TRIGGER_ROTATE_DEGREES = 68
TRIGGER_ROTATE_TIMES_360 = 69
TRIGGER_ROTATE_DO_LOCK_OBJECT_ROTATION = 70

TRIGGER_SECONDARY_GROUP_ID = 71

TRIGGER_FOLLOW_MOD_X = 72
TRIGGER_FOLLOW_MOD_Y = 73

TRIGGER_SHAKE_STRENGTH = 75

TRIGGER_ANIMATION_ID = 76

TRIGGER_PICKUP_COUNT = 77
TRIGGER_PICKUP_DO_SUBSTRACT = 78
TRIGGER_PICKUP_MODE = 79

ITEM_OR_BLOCK_ID = 80

TRIGGER_TOUCH_DO_HOLD_MODE = 81
TRIGGER_TOUCH_TOGGLE_MODE = 82

TRIGGER_SHAKE_INTERVAL = 84

TRIGGER_EASING_RATE = 85

TRIGGER_PULSE_EXCLUSIVE = 86

TRIGGER_INSTANT_COUNT_COMPARISON = 88

TRIGGER_TOUCH_IS_DUAL = 89

TRIGGER_FOLLOW_PLAYER_Y_SPEED = 90
TRIGGER_FOLLOW_PLAYER_Y_DELAY = 91
TRIGGER_FOLLOW_PLAYER_Y_OFFSET = 92

TRIGGER_COLLISION_DO_TRIGGER_ON_EXIT = 93
COLLISION_BLOCK_IS_DYNAMIC = 94
TRIGGER_COLLISION_BLOCK_B_ID = 95

IS_GLOW_DISABLED = 96

CUSTOM_ROTATION_DEGREES_PER_SECOND = 97
IS_ROTATION_DISABLED = 98

IS_ORG_MULTI_ACTIVATE = 99

TRIGGER_MOVE_DO_USE_TARGET = 100
TRIGGER_MOVE_TARGET_POS_COORDINATES = 101

TRIGGER_SPAWN_IS_DISABLED_IN_EDITOR = 102
IS_HIGH_DETAIL_ONLY = 103

TRIGGER_IS_MULTI = 104

TRIGGER_FOLLOW_PLAYER_Y_MAX_SPEED = 105

ANIMATION_RANDOMIZE_START = 106
ANIMATION_SPEED = 107

LINKED_GROUP_ID = 108

SCALE_X = 128
SCALE_Y = 129