K_ID = 1
K_POS_X = 2
K_POS_Y = 3
K_ROTATION_DEGREES = 6

K_COLOR_CHANNEL_DETAIL = 21
K_COLOR_CHANNEL_BASE = 22

K_HSV_DETAIL_ENABLED = 41
K_HSV_BASE_ENABLED = 42
K_HSV_DETAIL = 43
K_HSV_BASE = 44

K_GROUPS = 57

K_SCALE_X = 128
K_SCALE_Y = 129